### ISSUE TITLE
TODO List - Backend

### ISSUE THREAD

**Issue by dawid-kolcz** [dawid-kolcz/projekt-wtw#5]
- Backend must handle all action user wants to process
- [ ] adding new list
- [ ] adding new task to list
- [ ]  removing list
- [ ] removing tasks from list
- [ ] updateing list
- [ ] updateing tasks status
- [ ] saving list to history/archive
- [ ] saving taks to history/archive 

- Checking for logged user, non logged user must be redirected to login page
- [ ] logged user can procced to lists
- [ ] non logged user are redirected to login page
